# CLAP Linear Probing - Naive Bayes
experiment_name: "clap_lin_prob_nb"

# Model Configuration
model: "mert"
batch_size: 16 # For embedding extraction
max_duration: 10

# Dimensionality Reduction
pca:
  enabled: false
  n_components: 256

# Classification Algorithm
classifier:
  type: "nb"

  nb:
    var_smoothing: 1.0e-9
