"""
clap_zeroshot.py — Evaluate zero-shot classification performance of LAION CLAP.

Uses the 48000Hz raw audio arrays generated by prepare_mel.py (--clap-mode).
"""

import os
import sys
import argparse
import csv
import torch
import numpy as np
import yaml
from pathlib import Path
from typing import Any, Dict, List
from rich.progress import (
    Progress,
    TextColumn,
    BarColumn,
    TimeElapsedColumn,
    TimeRemainingColumn,
)
from transformers import AutoModel, AutoProcessor, ClapModel
from sklearn.metrics import classification_report, accuracy_score

# Add project root to sys.path
root_dir = str(Path(__file__).parents[1])
if root_dir not in sys.path:
    sys.path.append(root_dir)

# Mapping of short names to HuggingFace model IDs
MODEL_MAPPING = {
    "unfused": "laion/clap-htsat-unfused",
    "larger": "laion/larger_clap_music",
    "lukewys": "lukewys/laion_clap",
    "microsoft": "microsoft/clap-2023",
}


def load_config(paths: List[str]) -> Dict[str, Any]:
    """Loads and merges configuration parameters from multiple YAML files."""
    config: Dict[str, Any] = {}
    for path in paths:
        if not os.path.exists(path):
            continue
        with open(path, "r", encoding="utf-8") as f:
            loaded = yaml.safe_load(f)
            if loaded:
                config.update(loaded)
    return config


def load_test_data(metadata_path: Path, mel_dir: Path):
    """Loads the test set (Fold 0) metadata."""
    test_records = []
    with open(metadata_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if int(row["fold"]) == 0:
                npy_path = mel_dir / row["filename"]
                label = int(row["label"])
                test_records.append((npy_path, label))
    return test_records


def get_genres(metadata_path: Path):
    """Extracts sorted list of genres."""
    genres = set()
    with open(metadata_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            genres.add(row["genre"])
    return sorted(list(genres))


def main(args: argparse.Namespace):
    # Load configuration
    exp_config_path = os.path.join("configs", "clap_zeroshot", args.exp)
    if not exp_config_path.endswith((".yaml", ".yml")):
        exp_config_path += ".yaml"

    config = load_config([exp_config_path])

    # CLI Overrides
    model_key = str(args.model if args.model else config.get("model", "unfused"))
    model_id = str(MODEL_MAPPING.get(model_key, model_key))

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    print(f"Loading CLAP model: {model_id}...")

    # 1. Initialize Model and Processor
    # Use ClapModel class explicitly to ensure get_text_features/get_audio_features 
    # use the projected outputs
    processor: Any = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model: Any = ClapModel.from_pretrained(model_id, trust_remote_code=True).to(device)
    model.eval()

    mel_dir = Path("dataset/mel_clap")
    metadata_path = mel_dir / "metadata.csv"

    if not metadata_path.exists():
        print(
            "Error: metadata.csv not found. Run python scripts/prepare_mel.py --clap-mode first."
        )
        return

    # 2. Load Data
    test_records = load_test_data(metadata_path, mel_dir)
    genres = get_genres(metadata_path)
    print(f"Found {len(test_records)} test samples in Fold 0.")

    # 3. Prepare Text Prompts (Templates)
    template = str(
        args.template if args.template else config.get("template", "This is a {genre} song.")
    )
    print(f"Using template: '{template}'")

    text_prompts = [template.format(genre=genre) for genre in genres]

    # Pre-compute text embeddings for the labels
    print("Computing text embeddings for labels...")
    with torch.no_grad():
        text_inputs = processor(text=text_prompts, return_tensors="pt", padding=True)
        text_inputs = {k: v.to(device) for k, v in text_inputs.items()}
        
        text_features_out = model.get_text_features(**text_inputs)
        text_features = text_features_out.pooler_output
        text_features = text_features / text_features.norm(dim=-1, keepdim=True)

    y_true = []
    y_pred = []

    batch_size = int(args.batch_size if args.batch_size else config.get("batch_size", 16))
    max_duration = int(
        args.max_duration if args.max_duration else config.get("max_duration", 10)
    )

    # 4. Zero-Shot Inference Loop
    print("Starting zero-shot evaluation...")
    with Progress(
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        TextColumn("{task.completed}/{task.total}"),
        TimeElapsedColumn(),
        TextColumn("/"),
        TimeRemainingColumn(),
    ) as progress:
        total_batches = (len(test_records) + batch_size - 1) // batch_size
        task = progress.add_task("[cyan]Processing...", total=total_batches)

        for i in range(0, len(test_records), batch_size):
            batch_records = test_records[i : i + batch_size]
            batch_audios = []
            batch_labels = []

            for npy_path, label in batch_records:
                audio_array = np.load(npy_path)

                # Truncate to first max_duration (48kHz) to maintain original 0.56 accuracy
                max_samples = max_duration * 48000
                if len(audio_array) > max_samples:
                    audio_array = audio_array[:max_samples]

                batch_audios.append(audio_array)
                batch_labels.append(label)

            # Process audio separately
            audio_inputs = processor(
                audio=batch_audios,
                return_tensors="pt",
                padding=True,
                sampling_rate=48000,
            )
            audio_inputs = {k: v.to(device) for k, v in audio_inputs.items()}

            with torch.no_grad():
                audio_features_out = model.get_audio_features(**audio_inputs)
                audio_features = audio_features_out.pooler_output
                audio_features = audio_features / audio_features.norm(
                    dim=-1, keepdim=True
                )

                # Compute similarity using logit scale
                logit_scale = (
                    model.logit_scale_a.exp()
                    if hasattr(model, "logit_scale_a")
                    else 100.0
                )
                logits_per_audio = logit_scale * audio_features @ text_features.t()

                preds = logits_per_audio.argmax(dim=-1).cpu().numpy()

                y_pred.extend(preds)
                y_true.extend(batch_labels)

            progress.advance(task)

    # 5. Report Results
    acc = accuracy_score(y_true, y_pred)
    print("\n" + "=" * 50)
    print(f"Zero-Shot Accuracy: {acc:.4f}")
    print("=" * 50)

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=genres, zero_division=0))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Zero-shot Genre Classification with CLAP")
    parser.add_argument(
        "--exp", type=str, required=True, help="Config name (e.g., template_0)"
    )
    parser.add_argument(
        "--model",
        type=str,
        choices=list(MODEL_MAPPING.keys()),
        help="Model override (unfused, larger, lukewys, microsoft)",
    )
    parser.add_argument("--template", type=str, help="Prompt template override")
    parser.add_argument("--batch-size", type=int, help="Batch size override")
    parser.add_argument("--max-duration", type=int, help="Audio duration override (seconds)")
    args = parser.parse_args()
    main(args)
