"""
clap_zeroshot.py — Evaluate zero-shot classification performance of LAION CLAP.

Uses the 48000Hz raw audio arrays generated by prepare_mel.py (--clap-mode).
"""

import os
import sys
import argparse
import csv
import torch
import numpy as np
import yaml
from pathlib import Path
from typing import Any, Dict, List
from rich.progress import (
    Progress,
    TextColumn,
    BarColumn,
    TimeElapsedColumn,
    TimeRemainingColumn,
)
from transformers import AutoModel, AutoProcessor, ClapModel
from sklearn.metrics import classification_report, accuracy_score

# Add project root to sys.path
root_dir = str(Path(__file__).parents[1])
if root_dir not in sys.path:
    sys.path.append(root_dir)

# Mapping of short names to HuggingFace model IDs
MODEL_MAPPING = {
    "mert": "m-a-p/MERT-v1-330M",
    "larger": "laion/larger_clap_music",
    "lukewys": "lukewys/laion_clap",
    "microsoft": "microsoft/clap-2023",
}


def load_config(paths: List[str]) -> Dict[str, Any]:
    """Loads and merges configuration parameters from multiple YAML files."""
    config: Dict[str, Any] = {}
    for path in paths:
        if not os.path.exists(path):
            print(f"Warning: Config file {path} not found.")
            continue
        with open(path, "r", encoding="utf-8") as f:
            loaded = yaml.safe_load(f)
            if loaded:
                for key, value in loaded.items():
                    if (
                        key in config
                        and isinstance(config[key], dict)
                        and isinstance(value, dict)
                    ):
                        config[key].update(value)
                    else:
                        config[key] = value
    return config


def load_test_data(metadata_path: Path, mel_dir: Path):
    """Loads the test set (Fold 0) metadata and returns paths and labels."""
    test_records = []
    with open(metadata_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if int(row["fold"]) == 0:
                npy_path = mel_dir / row["filename"]
                label = int(row["label"])
                test_records.append((npy_path, label))
    return test_records


def get_genres(metadata_path: Path):
    """Extracts the sorted list of genres to map indices to string names."""
    genres = set()
    with open(metadata_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            genres.add(row["genre"])
    return sorted(list(genres))


def main(args: argparse.Namespace):
    # Load configuration
    exp_config_path = os.path.join("configs", "clap_zeroshot", args.exp)
    if not exp_config_path.endswith((".yaml", ".yml")):
        exp_config_path += ".yaml"

    if not os.path.exists(exp_config_path):
        print(f"Error: Experiment config not found at {exp_config_path}")
        return

    config = load_config([exp_config_path])

    # CLI Overrides
    if args.model is not None:
        config["model"] = args.model
    if args.template is not None:
        config["template"] = args.template
    if args.batch_size is not None:
        config["batch_size"] = args.batch_size
    if args.max_duration is not None:
        config["max_duration"] = args.max_duration

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    print(f"Experiment Config: {args.exp}")

    mel_dir = Path(config.get("mel_dir", "dataset/mel_clap"))
    metadata_path = Path(config.get("metadata_path", "dataset/mel_clap/metadata.csv"))

    if not metadata_path.exists():
        print(
            f"Error: {metadata_path} not found. Please run: python scripts/prepare_mel.py --clap-mode"
        )
        return

    # Load data
    test_records = load_test_data(metadata_path, mel_dir)
    genres = get_genres(metadata_path)
    print(f"Found {len(test_records)} test samples in Fold 0.")
    print(f"Genres: {genres}")

    # Prepare text prompts
    template = config.get("template", "This is a {genre} song.")
    print(f"Using template: '{template}'")
    text_prompts = [template.format(genre=genre) for genre in genres]

    # Initialize Model
    model_key = str(config.get("model", "mert"))
    model_id = str(MODEL_MAPPING.get(model_key, model_key))
    print(f"Loading model: {model_key} ({model_id})...")
    import typing

    processor: typing.Any = AutoProcessor.from_pretrained(model_id, trust_remote_code=True)
    model: typing.Any = AutoModel.from_pretrained(model_id, trust_remote_code=True)
    model = model.to(device)
    model.eval()

    # Pre-compute text embeddings for the prompts
    # Note: Zero-shot classification requires a text encoder (CLAP).
    # MERT is an audio encoder only and will require a linear probe later.
    if not hasattr(model, "get_text_features"):
        print(f"\n[!] Error: Model '{model_key}' does not have a text encoder for zero-shot tasks.")
        print(f"    Zero-shot similarity requires a CLAP-style model (e.g., larger, lukewys, microsoft).")
        print(f"    '{model_key}' can be used for feature extraction and linear probing in the future.")
        return

    print("Computing text embeddings...")
    with torch.no_grad():
        text_inputs = processor(text=text_prompts, return_tensors="pt", padding=True)
        text_inputs = {k: v.to(device) for k, v in text_inputs.items()}
        # get_text_features returns BaseModelOutputWithPooling; we need the pooler_output tensor
        text_features_out = model.get_text_features(**text_inputs)
        text_features = text_features_out.pooler_output
        text_features = text_features / text_features.norm(dim=-1, keepdim=True)

    y_true = []
    y_pred = []

    batch_size = config.get("batch_size", 16)
    max_duration = config.get("max_duration", 10)

    # Inference Loop
    print("Starting zero-shot inference...")
    with Progress(
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
        TextColumn("{task.completed}/{task.total}"),
        TimeElapsedColumn(),
        TextColumn("/"),
        TimeRemainingColumn(),
    ) as progress:
        total_batches = (len(test_records) + batch_size - 1) // batch_size
        task = progress.add_task("[cyan]Processing...", total=total_batches)

        for i in range(0, len(test_records), batch_size):
            batch_records = test_records[i : i + batch_size]
            batch_audios = []
            batch_labels = []

            for npy_path, label in batch_records:
                audio_array = np.load(npy_path)

                # Optional: truncate audio to max_duration to avoid OOM or processor limits
                max_samples = max_duration * 48000
                if len(audio_array) > max_samples:
                    # Take middle segment
                    start = (len(audio_array) - max_samples) // 2
                    audio_array = audio_array[start : start + max_samples]

                batch_audios.append(audio_array)
                batch_labels.append(label)

            # Process audio (using 'audio' instead of deprecated 'audios')
            audio_inputs = processor(
                audio=batch_audios,
                return_tensors="pt",
                padding=True,
                sampling_rate=48000,
            )
            audio_inputs = {k: v.to(device) for k, v in audio_inputs.items()}

            with torch.no_grad():
                audio_features_out = model.get_audio_features(**audio_inputs)
                audio_features = audio_features_out.pooler_output
                audio_features = audio_features / audio_features.norm(
                    dim=-1, keepdim=True
                )

                # Cosine similarity between audio and text
                # We use logit_scale_a as the multiplier for audio-to-text similarity
                logit_scale = model.logit_scale_a.exp()
                logits_per_audio = logit_scale * audio_features @ text_features.t()

                preds = logits_per_audio.argmax(dim=-1).cpu().numpy()

                y_pred.extend(preds)
                y_true.extend(batch_labels)

            progress.advance(task)

    # Evaluate
    acc = accuracy_score(y_true, y_pred)
    print("\n" + "=" * 50)
    print(f"Zero-Shot Accuracy: {acc:.4f}")
    print("=" * 50)

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred, target_names=genres))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Evaluation pipeline for pretrained audio-text models (MERT, CLAP)."
    )
    parser.add_argument(
        "--exp",
        type=str,
        required=True,
        help="Experiment config name (e.g., template_0).",
    )
    parser.add_argument(
        "--model",
        type=str,
        choices=list(MODEL_MAPPING.keys()),
        help="Pretrained model to use (mert, larger, lukewys, microsoft). Default is 'mert'.",
    )
    parser.add_argument(
        "--template",
        type=str,
        help="Override the prompt template string for zero-shot similarity.",
    )
    parser.add_argument(
        "--batch-size", type=int, help="Override batch size for inference."
    )
    parser.add_argument(
        "--max-duration",
        type=int,
        help="Override max duration in seconds to feed to CLAP.",
    )
    args = parser.parse_args()
    main(args)
