# Experiment: CLAP Zero-Shot using Template 5
experiment_name: "clap_zeroshot_t5"

# Model Configuration
model_id: "laion/clap-htsat-unfused"
model: mert

# Evaluation Configuration
template: "Listen to this {genre} track."
batch_size: 16
max_duration: 10

# Data Configuration
mel_dir: "dataset/mel_clap"
metadata_path: "dataset/mel_clap/metadata.csv"
